### ISSUE TITLE
Changing Merc name\stats and dmg

### ISSUE THREAD

**Issue by badkittykkr** [AlexisEvo/d2r-loot-filter#15] opened 2022-05-19 21:13 UTC
I noticed today my Act2 mercs name is GUARD and is 95% to lvl 92 (i'm lvl 91) and cannot equip Infinity. My +40 Nova is also only 2700dmg., down from 5400 fully buffed.  I couldn't figure it out. SO i deleted "-mod lootfilter -txt" from launcher...and guards name is normal, can equip infinity and my damage is normal.

Just checked amazon and her merc...all is normal on her.

i've restarted several times with and without the "-mod lootfilter -txt" and it does it every time

This is a HUGE bug since i can't equip infinity to merc.....  unless this mod is dead...then it's finally dead

**Comment by d2inventory** [comment] 2022-06-04 13:24
I can't reproduce the issue, are you using the latest version? Did you delete the existing folder and then copied new instead of simply overwriting?

**Comment by badkittykkr** [comment] 2022-06-05 06:39
i did delete the existing folder and  copied new. It's fine. Thanks.

**Comment by AlexisEvo** [comment] 2022-06-07 05:19
Yeah after the ladder launch there were many issues but most have been resolved with the latest update, reinstall if you're having problems.

**Closed by AlexisEvo** 2022-06-07 05:19 UTC
